/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardSummary {
  'lowStockCount' : bigint,
  'totalStock' : bigint,
  'totalItems' : bigint,
  'nearExpiryCount' : bigint,
}
export interface Item {
  'id' : ItemId,
  'sku' : string,
  'expiryDate' : [] | [bigint],
  'name' : string,
  'unit' : string,
  'minStock' : bigint,
  'category' : string,
  'currentStock' : bigint,
}
export type ItemId = bigint;
export interface ItemInput {
  'sku' : string,
  'expiryDate' : [] | [bigint],
  'name' : string,
  'unit' : string,
  'minStock' : bigint,
  'category' : string,
}
export interface StockMovement {
  'id' : bigint,
  'itemId' : ItemId,
  'date' : bigint,
  'note' : string,
  'movementType' : { 'in' : null } |
    { 'out' : null },
  'quantity' : bigint,
}
export type StockStatus = { 'low' : null } |
  { 'safe' : null };
export interface _SERVICE {
  '__items' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Item>>,
  '__movements' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<StockMovement>
  >,
  '__state' : ActorMethod<[], any>,
  'createItem' : ActorMethod<
    [ItemInput],
    { 'ok' : ItemId } |
      { 'err' : { 'invalidData' : string } }
  >,
  'deleteItem' : ActorMethod<[ItemId], boolean>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getItem' : ActorMethod<[ItemId], [] | [Item]>,
  'getItemStockHistory' : ActorMethod<[ItemId], Array<StockMovement>>,
  'getMovementReport' : ActorMethod<[bigint, bigint], Array<StockMovement>>,
  'getNearExpiryItems' : ActorMethod<[], Array<Item>>,
  'getStockReport' : ActorMethod<
    [[] | [string], [] | [StockStatus]],
    Array<Item>
  >,
  'listItems' : ActorMethod<[], Array<Item>>,
  'listStockIn' : ActorMethod<[], Array<StockMovement>>,
  'listStockOut' : ActorMethod<[], Array<StockMovement>>,
  'recordStockIn' : ActorMethod<[ItemId, bigint, bigint, string], boolean>,
  'recordStockOut' : ActorMethod<[ItemId, bigint, bigint, string], boolean>,
  'updateItem' : ActorMethod<
    [ItemId, ItemInput],
    { 'ok' : boolean } |
      { 'err' : { 'invalidData' : string } }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];