/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ItemId = IDL.Nat;
export const Item = IDL.Record({
  'id' : ItemId,
  'sku' : IDL.Text,
  'expiryDate' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'minStock' : IDL.Nat,
  'category' : IDL.Text,
  'currentStock' : IDL.Nat,
});
export const StockMovement = IDL.Record({
  'id' : IDL.Nat,
  'itemId' : ItemId,
  'date' : IDL.Int,
  'note' : IDL.Text,
  'movementType' : IDL.Variant({ 'in' : IDL.Null, 'out' : IDL.Null }),
  'quantity' : IDL.Nat,
});
export const ItemInput = IDL.Record({
  'sku' : IDL.Text,
  'expiryDate' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'minStock' : IDL.Nat,
  'category' : IDL.Text,
});
export const DashboardSummary = IDL.Record({
  'lowStockCount' : IDL.Nat,
  'totalStock' : IDL.Nat,
  'totalItems' : IDL.Nat,
  'nearExpiryCount' : IDL.Nat,
});
export const StockStatus = IDL.Variant({ 'low' : IDL.Null, 'safe' : IDL.Null });

export const idlService = IDL.Service({
  '__items' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Item)],
      ['query'],
    ),
  '__movements' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(StockMovement)],
      ['query'],
    ),
  '__state' : IDL.Func([], [IDL.Reserved], ['query']),
  'createItem' : IDL.Func(
      [ItemInput],
      [
        IDL.Variant({
          'ok' : ItemId,
          'err' : IDL.Variant({ 'invalidData' : IDL.Text }),
        }),
      ],
      [],
    ),
  'deleteItem' : IDL.Func([ItemId], [IDL.Bool], []),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getItem' : IDL.Func([ItemId], [IDL.Opt(Item)], ['query']),
  'getItemStockHistory' : IDL.Func(
      [ItemId],
      [IDL.Vec(StockMovement)],
      ['query'],
    ),
  'getMovementReport' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(StockMovement)],
      ['query'],
    ),
  'getNearExpiryItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getStockReport' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(StockStatus)],
      [IDL.Vec(Item)],
      ['query'],
    ),
  'listItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'listStockIn' : IDL.Func([], [IDL.Vec(StockMovement)], ['query']),
  'listStockOut' : IDL.Func([], [IDL.Vec(StockMovement)], ['query']),
  'recordStockIn' : IDL.Func(
      [ItemId, IDL.Nat, IDL.Int, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'recordStockOut' : IDL.Func(
      [ItemId, IDL.Nat, IDL.Int, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateItem' : IDL.Func(
      [ItemId, ItemInput],
      [
        IDL.Variant({
          'ok' : IDL.Bool,
          'err' : IDL.Variant({ 'invalidData' : IDL.Text }),
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ItemId = IDL.Nat;
  const Item = IDL.Record({
    'id' : ItemId,
    'sku' : IDL.Text,
    'expiryDate' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'minStock' : IDL.Nat,
    'category' : IDL.Text,
    'currentStock' : IDL.Nat,
  });
  const StockMovement = IDL.Record({
    'id' : IDL.Nat,
    'itemId' : ItemId,
    'date' : IDL.Int,
    'note' : IDL.Text,
    'movementType' : IDL.Variant({ 'in' : IDL.Null, 'out' : IDL.Null }),
    'quantity' : IDL.Nat,
  });
  const ItemInput = IDL.Record({
    'sku' : IDL.Text,
    'expiryDate' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'minStock' : IDL.Nat,
    'category' : IDL.Text,
  });
  const DashboardSummary = IDL.Record({
    'lowStockCount' : IDL.Nat,
    'totalStock' : IDL.Nat,
    'totalItems' : IDL.Nat,
    'nearExpiryCount' : IDL.Nat,
  });
  const StockStatus = IDL.Variant({ 'low' : IDL.Null, 'safe' : IDL.Null });
  
  return IDL.Service({
    '__items' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Item)],
        ['query'],
      ),
    '__movements' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(StockMovement)],
        ['query'],
      ),
    '__state' : IDL.Func([], [IDL.Reserved], ['query']),
    'createItem' : IDL.Func(
        [ItemInput],
        [
          IDL.Variant({
            'ok' : ItemId,
            'err' : IDL.Variant({ 'invalidData' : IDL.Text }),
          }),
        ],
        [],
      ),
    'deleteItem' : IDL.Func([ItemId], [IDL.Bool], []),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getItem' : IDL.Func([ItemId], [IDL.Opt(Item)], ['query']),
    'getItemStockHistory' : IDL.Func(
        [ItemId],
        [IDL.Vec(StockMovement)],
        ['query'],
      ),
    'getMovementReport' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(StockMovement)],
        ['query'],
      ),
    'getNearExpiryItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getStockReport' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(StockStatus)],
        [IDL.Vec(Item)],
        ['query'],
      ),
    'listItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'listStockIn' : IDL.Func([], [IDL.Vec(StockMovement)], ['query']),
    'listStockOut' : IDL.Func([], [IDL.Vec(StockMovement)], ['query']),
    'recordStockIn' : IDL.Func(
        [ItemId, IDL.Nat, IDL.Int, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'recordStockOut' : IDL.Func(
        [ItemId, IDL.Nat, IDL.Int, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateItem' : IDL.Func(
        [ItemId, ItemInput],
        [
          IDL.Variant({
            'ok' : IDL.Bool,
            'err' : IDL.Variant({ 'invalidData' : IDL.Text }),
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };