/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Item {
    id: ItemId;
    sku: string;
    expiryDate?: bigint;
    name: string;
    unit: string;
    minStock: bigint;
    category: string;
    currentStock: bigint;
}
export interface DashboardSummary {
    lowStockCount: bigint;
    totalStock: bigint;
    totalItems: bigint;
    nearExpiryCount: bigint;
}
export interface StockMovement {
    id: bigint;
    itemId: ItemId;
    date: bigint;
    note: string;
    movementType: Variant_in_out;
    quantity: bigint;
}
export type ItemId = bigint;
export interface ItemInput {
    sku: string;
    expiryDate?: bigint;
    name: string;
    unit: string;
    minStock: bigint;
    category: string;
}
export enum StockStatus {
    low = "low",
    safe = "safe"
}
export enum Variant_in_out {
    in_ = "in",
    out = "out"
}
export interface backendInterface {
    __items(io: bigint | null, count: bigint | null): Promise<Array<Item>>;
    __movements(io: bigint | null, count: bigint | null): Promise<Array<StockMovement>>;
    __state(): Promise<any>;
    createItem(input: ItemInput): Promise<{
        __kind__: "ok";
        ok: ItemId;
    } | {
        __kind__: "err";
        err: {
            __kind__: "invalidData";
            invalidData: string;
        };
    }>;
    deleteItem(id: ItemId): Promise<boolean>;
    getDashboardSummary(): Promise<DashboardSummary>;
    getItem(id: ItemId): Promise<Item | null>;
    getItemStockHistory(itemId: ItemId): Promise<Array<StockMovement>>;
    getMovementReport(startDate: bigint, endDate: bigint): Promise<Array<StockMovement>>;
    getNearExpiryItems(): Promise<Array<Item>>;
    getStockReport(category: string | null, status: StockStatus | null): Promise<Array<Item>>;
    listItems(): Promise<Array<Item>>;
    listStockIn(): Promise<Array<StockMovement>>;
    listStockOut(): Promise<Array<StockMovement>>;
    recordStockIn(itemId: ItemId, quantity: bigint, date: bigint, note: string): Promise<boolean>;
    recordStockOut(itemId: ItemId, quantity: bigint, date: bigint, note: string): Promise<boolean>;
    updateItem(id: ItemId, input: ItemInput): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: {
            __kind__: "invalidData";
            invalidData: string;
        };
    }>;
}
import type { Item as _Item, ItemId as _ItemId, ItemInput as _ItemInput, StockMovement as _StockMovement, StockStatus as _StockStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __items(arg0: bigint | null, arg1: bigint | null): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.__items(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__items(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __movements(arg0: bigint | null, arg1: bigint | null): Promise<Array<StockMovement>> {
        if (this.processError) {
            try {
                const result = await this.actor.__movements(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__movements(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async __state(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__state();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__state();
            return result;
        }
    }
    async createItem(arg0: ItemInput): Promise<{
        __kind__: "ok";
        ok: ItemId;
    } | {
        __kind__: "err";
        err: {
            __kind__: "invalidData";
            invalidData: string;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createItem(to_candid_ItemInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createItem(to_candid_ItemInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteItem(arg0: ItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItem(arg0);
            return result;
        }
    }
    async getDashboardSummary(): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return result;
        }
    }
    async getItem(arg0: ItemId): Promise<Item | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItem(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItem(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemStockHistory(arg0: ItemId): Promise<Array<StockMovement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemStockHistory(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemStockHistory(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMovementReport(arg0: bigint, arg1: bigint): Promise<Array<StockMovement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMovementReport(arg0, arg1);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMovementReport(arg0, arg1);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNearExpiryItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearExpiryItems();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearExpiryItems();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStockReport(arg0: string | null, arg1: StockStatus | null): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockReport(to_candid_opt_n15(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockReport(to_candid_opt_n15(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async listItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.listItems();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listItems();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStockIn(): Promise<Array<StockMovement>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStockIn();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStockIn();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStockOut(): Promise<Array<StockMovement>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStockOut();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStockOut();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordStockIn(arg0: ItemId, arg1: bigint, arg2: bigint, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.recordStockIn(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordStockIn(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async recordStockOut(arg0: ItemId, arg1: bigint, arg2: bigint, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.recordStockOut(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordStockOut(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateItem(arg0: ItemId, arg1: ItemInput): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: {
            __kind__: "invalidData";
            invalidData: string;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItem(arg0, to_candid_ItemInput_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItem(arg0, to_candid_ItemInput_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Item_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Item): Item {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_StockMovement_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockMovement): StockMovement {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Item]): Item | null {
    return value.length === 0 ? null : from_candid_Item_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    sku: string;
    expiryDate: [] | [bigint];
    name: string;
    unit: string;
    minStock: bigint;
    category: string;
    currentStock: bigint;
}): {
    id: ItemId;
    sku: string;
    expiryDate?: bigint;
    name: string;
    unit: string;
    minStock: bigint;
    category: string;
    currentStock: bigint;
} {
    return {
        id: value.id,
        sku: value.sku,
        expiryDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.expiryDate)),
        name: value.name,
        unit: value.unit,
        minStock: value.minStock,
        category: value.category,
        currentStock: value.currentStock
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    itemId: _ItemId;
    date: bigint;
    note: string;
    movementType: {
        in: null;
    } | {
        out: null;
    };
    quantity: bigint;
}): {
    id: bigint;
    itemId: ItemId;
    date: bigint;
    note: string;
    movementType: Variant_in_out;
    quantity: bigint;
} {
    return {
        id: value.id,
        itemId: value.itemId,
        date: value.date,
        note: value.note,
        movementType: from_candid_variant_n9(_uploadFile, _downloadFile, value.movementType),
        quantity: value.quantity
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ItemId;
} | {
    err: {
        invalidData: string;
    };
}): {
    __kind__: "ok";
    ok: ItemId;
} | {
    __kind__: "err";
    err: {
        __kind__: "invalidData";
        invalidData: string;
    };
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_variant_n13(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidData: string;
}): {
    __kind__: "invalidData";
    invalidData: string;
} {
    return "invalidData" in value ? {
        __kind__: "invalidData",
        invalidData: value.invalidData
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: {
        invalidData: string;
    };
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: {
        __kind__: "invalidData";
        invalidData: string;
    };
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_variant_n13(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    in: null;
} | {
    out: null;
}): Variant_in_out {
    return "in" in value ? Variant_in_out.in : "out" in value ? Variant_in_out.out : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Item>): Array<Item> {
    return value.map((x)=>from_candid_Item_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StockMovement>): Array<StockMovement> {
    return value.map((x)=>from_candid_StockMovement_n7(_uploadFile, _downloadFile, x));
}
function to_candid_ItemInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemInput): _ItemInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_StockStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockStatus): _StockStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockStatus | null): [] | [_StockStatus] {
    return value === null ? candid_none() : candid_some(to_candid_StockStatus_n17(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sku: string;
    expiryDate?: bigint;
    name: string;
    unit: string;
    minStock: bigint;
    category: string;
}): {
    sku: string;
    expiryDate: [] | [bigint];
    name: string;
    unit: string;
    minStock: bigint;
    category: string;
} {
    return {
        sku: value.sku,
        expiryDate: value.expiryDate ? candid_some(value.expiryDate) : candid_none(),
        name: value.name,
        unit: value.unit,
        minStock: value.minStock,
        category: value.category
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockStatus): {
    low: null;
} | {
    safe: null;
} {
    return value == StockStatus.low ? {
        low: null
    } : value == StockStatus.safe ? {
        safe: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
